
name: Publish to npm registry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          registry-url: https://registry.npmjs.org/


      - name: git config
        run: |
          git config --global user.email "shibisuriya.work@gmail.com"
          git config --global user.name "shibisuriya"


      - name: Publish package to npm registry
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
